Create Repositories.md
microsoftgraph/msgraph-sdk-design pull request #54
Opened 2021-08-30 23:55 UTC by nikithauc

Creating a document to record the design and decisions for the repository set up.

2021-08-31 05:35 UTC, SilasKenneth commented on Repositories.md
> +- Graph service library containing Kiota generated the request builders.
```suggestion
- Graph service library containing Kiota generated request builders.
```

2021-08-31 11:54 UTC, baywet requested changes
Thanks for putting all of this together! A couple of suggestions on the doc itself, and in addition to that, maybe we should add a link to that doc on one of the main pages to make it discoverable?

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +- Kiota generator
```suggestion

- Kiota generator
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +
```suggestion
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +1. Duplicate names - Consider adding new repositories for all the Kiota generated libraries and discontinuing the repos that use the current code generation process.
in that case I suggest we rename the repo whenever we release to align with the other languages

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +- kiota-<language>
```suggestion
- kiota-<language> : contains the abstractions and core implementation packages
```

2021-08-31 11:54 UTC, baywet commented on Repositories.md
> +- (optional) msgraph-china-sdk-<language>
```suggestion
- (optional) msgraph-china-sdk-<language>: an advantage of Kiota based generation is we can deliver SDKs tailored to customers' environments, this includes the ability to ship one service library per national cloud per version as national clouds generally have access to fewer endpoints.
```

2021-08-31 20:14 UTC, MIchaelMainer commented
For cloud specific SDKs that are not the public cloud, I suggest: msgraph{-beta}-{cloud name}-sdk-{language}.

With the Kiota onboarding, our code will be using the following four solutions:
 - Kiota generator
 - Kiota core libraries for each language - these are the common core HTTP client options for any client generated with *Kiota generator*.
 - Graph core library for each language which will be depending on the *Kiota core* libraries of the same language. These are the Graph specific implementations that provide Graph specific functionality.
-  Graph service library containing Kiota generated the request builders.

The name change game goes beyond repos. We need to consider whether the Kiota generated libraries and experience is a continuation of our existing libraries and experience, or is this an entirely new client library experience that requires us to divorce some or all of our existing experiences. We have accumulated many years worth of names, patterns, links, and other artifacts indexed across the Internet -- there is value in maintaining a relationship to those artifacts. There is value in a clean break. There will be confusion either way as we'd be introducing a change -- we need to think hard about how we mitigate that confusion. My default is to try to keep our existing names and links, and make sure we have a clear version upgrade that is well documented and discoverable.

2021-09-01 11:56 UTC, baywet commented
@MIchaelMainer on the naming comment you made: I believe that for languages that already have a fluent story today, the kiota based version is just a new iteration of that and would should reuse the names (dotnet, java,...). For other languages that don't have a fluent API story today, we should align, either by creating the new libs/repos if inexistent, or by renaming the existing repos if they are in the way of being aligned with other languages.

2024-08-01 15:31 UTC, baywet commented on Repositories.md
> +1. Duplicate names - Consider adding new repositories for all the Kiota generated libraries and discontinuing the repos that use the current code generation process.
```suggestion
1. Duplicate names - Consider adding new repositories for all the Kiota generated libraries and discontinuing the repos that use the current code generation process. Also consider renaming the older repository.
```

2024-08-01 15:31 UTC, merged