update PageIterator docs
microsoftgraph/msgraph-sdk-design pull request #73
Opened 2022-02-02 14:00 UTC by jobala

2022-02-02 14:04 UTC, baywet submitted a review, later dismissed

2022-02-02 15:50 UTC, baywet requested changes

2022-02-02 15:50 UTC, baywet commented on tasks/PageIteratorTask.md
> +6. Provide a **Next** method that returns the next item the current page or the next page.
```suggestion
6. Provide a **Next** method that returns the next item from the current page or the next page.
```

2022-02-03 19:14 UTC, ddyett commented
do you maybe want to add an example for Go.

2022-02-04 14:27 UTC, calebkiage submitted a review, later dismissed

2022-02-04 14:43 UTC, baywet approved these changes

2022-02-07 13:32 UTC, baywet approved these changes

2022-02-07 18:52 UTC, merged