Add samples for PHP page iterator.
microsoftgraph/msgraph-sdk-design pull request #78
Opened 2022-09-01 12:35 UTC by SilasKenneth

2022-09-01 15:23 UTC, baywet requested changes

2022-09-01 15:23 UTC, baywet commented on tasks/PageIteratorTask.md
> +      return true;
I don't think we should expect the page iterator consumer to deserialize models themselves, this is something we should be doing for them.
Granted they might have to downcast if the generic types support in PHP is not very advanced

2022-09-06 16:04 UTC, baywet requested changes

2022-09-06 16:04 UTC, baywet commented on tasks/PageIteratorTask.md
>      | C#          | -                    |
```suggestion
    | C#          | Implemented |
```

2022-09-06 16:04 UTC, baywet commented on tasks/PageIteratorTask.md
>      | JAVA        | -                    |
```suggestion
    | JAVA        | Implemented |
```

2022-09-18 13:38 UTC, BertsLifee approved these changes

2022-09-18 14:11 UTC, BertsLifee approved these changes

2022-09-27 12:43 UTC, merged